name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13.x]
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build restaurants-service
        run: |
          cd restaurants-service && ./gradlew clean build -x check
      - name: deploy restaurants-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: pickmeRestaurantFunction
          zip_file: restaurants-service/build/distributions/restaurants-service.zip
      - name: Build delivery-service
        run: |
          cd delivery-service && ./gradlew clean build -x check
      - name: deploy delivery-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: pickmeDeliveryFunction
          zip_file: delivery-service/build/distributions/delivery-service.zip
      - name: Build order-service
        run: |
          cd order-service && ./gradlew clean build -x check
      - name: deploy order-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: pickmePlaceOrderFunction
          zip_file: order-service/build/distributions/order-service.zip

