name: deploy to lambda
on: [ push ]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # Restaurant service
      - name: Set environment variables for Restaurant Service Lambda function
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.DEV_RESTAURANT_LAMBDA_NAME }} \
            --environment "Variables={DBHOST=${{ secrets.DEV_DBHOST }},USERNAME=${{ secrets.DEV_USERNAME }}, PW=${{ secrets.DEV_PW }}}"
      - name: Build restaurants-service
        run: |
          cd restaurants-service && ./gradlew clean build -x check
      - name: deploy restaurants-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.DEV_RESTAURANT_LAMBDA_NAME }}
          zip_file: restaurants-service/build/distributions/restaurants-service.zip
      # Delivery service
      - name: Set environment variables for Delivery Service Lambda function
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.DEV_DELIVERY_LAMBDA_NAME }} \
            --environment "Variables={DBHOST=${{ secrets.DEV_DBHOST }},USERNAME=${{ secrets.DEV_USERNAME }}, PW=${{ secrets.DEV_PW }}}"
      - name: Build delivery-service
        run: |
          cd delivery-service && ./gradlew clean build -x check
      - name: deploy delivery-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.DEV_DELIVERY_LAMBDA_NAME }}
          zip_file: delivery-service/build/distributions/delivery-service.zip
      # Order service
      - name: Set environment variables for Delivery Service Lambda function
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.DEV_ORDER_LAMBDA_NAME }} \
            --environment "Variables={DBHOST=${{ secrets.DEV_DBHOST }},USERNAME=${{ secrets.DEV_USERNAME }}, PW=${{ secrets.DEV_PW }}}"
      - name: Build order-service
        run: |
          cd order-service && ./gradlew clean build -x check
      - name: deploy order-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.DEV_ORDER_LAMBDA_NAME }}
          zip_file: order-service/build/distributions/order-service.zip
      # Check order status service
      - name: Set environment variables for Delivery Service Lambda function
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ secrets.DEV_CHANGE_ORDER_STATUS_LAMBDA_NAME }} \
            --environment "Variables={DBHOST=${{ secrets.DEV_DBHOST }},USERNAME=${{ secrets.DEV_USERNAME }}, PW=${{ secrets.DEV_PW }}}
      - name: Build order-status-service
        run: |
          cd order-status-service && ./gradlew clean build -x check
      - name: deploy order-status-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.DEV_CHANGE_ORDER_STATUS_LAMBDA_NAME }}
          zip_file: order-status-service/build/distributions/order-status-service.zip

