name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Set environment variables for Restaurant Service Lambda function
        run: |
          aws lambda update-function-configuration \
            --function-name pickmeRestaurantFunction \
            --environment Variables={DBHOST=${{ secrets.DEV_DBHOST }},USERNAME=${{ secrets.DEV_USERNAME }}, PW=${{ secrets.DEV_PW }}}
      - name: Build restaurants-service
        run: |
          cd restaurants-service && ./gradlew clean build -x check
      - name: deploy restaurants-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: pickmeRestaurantFunction
          zip_file: restaurants-service/build/distributions/restaurants-service.zip
      - name: Build delivery-service
        run: |
          cd delivery-service && ./gradlew clean build -x check
      - name: deploy delivery-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: pickmeDeliveryFunction
          zip_file: delivery-service/build/distributions/delivery-service.zip
      - name: Build order-service
        run: |
          cd order-service && ./gradlew clean build -x check
      - name: deploy order-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: pickmeOrderFunction
          zip_file: order-service/build/distributions/order-service.zip
      - name: Build order-status-service
        run: |
          cd order-status-service && ./gradlew clean build -x check
      - name: deploy order-status-service
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: pickmeChangeOrderStatusFunction
          zip_file: order-status-service/build/distributions/order-status-service.zip

